### ISSUE TITLE
Don't display "null" values.

### ISSUE THREAD

**Issue by tanja3981** [zreptil/nightscout-reporter#1]
When I select nothing in the settings for insulin/birthday/... "null" is shown in the report. 
Better would be to display nothing instead.

**Comment by zreptil** [comment]
Thats right, but due to the design of the page, i cannot leave it completley empty (the pdfmake would change the layout on the page). But i am thinking about a solution for this. Thanks for the hint :)

**Comment by zreptil** [comment]
In Version 1.0.3 the layout changed and now it works as expected.
