### ISSUE TITLE
Glucose Perzentil Diagram (AGP) Falschfarben

### ISSUE THREAD

**Issue by LongboatAline** [zreptil/nightscout-reporter#10]
### Platform: MacOS X. Chrome, Preview, Skim
Der Hintergrund des Zielbereiches im AGP ist, je nach Darstellendem Programm, korrekt oder invertiert. Besonders nett ist die Darstellung durch das "Preview" Programm unter MacOS X - da wird die Graphik in der Übersichtsdarstellung der einzelseiten "richtig" dargestellt, aber in der Seitenansicht invertiert. Lustig... 

### PDF Preview in Chrome unter MacOS X
![agp-chrome - nightscout reporter](https://user-images.githubusercontent.com/35570803/53248007-fee5d880-36b4-11e9-800c-f7054f5bb8f6.jpg)

### Skim PDF reader 
![agp-skim - nightscout reporter](https://user-images.githubusercontent.com/35570803/53248064-25a40f00-36b5-11e9-84af-1b2e4b00bfb6.jpg)

### Preview unter MacOS X
![preview - unknown](https://user-images.githubusercontent.com/35570803/53248142-4ff5cc80-36b5-11e9-884e-2b761c7b1bc7.jpg)
unter MacOS X

**Comment by zreptil** [comment]
Das verwundert mich. Sowas ist bei mir noch nicht vorgekommen. Die Farben werden im Code als RGB Werte definiert und können dann eigentlich nur noch vom darstellenden Programm falsch interpretiert werden. Ich werde mir das mal anschauen und ein bisschen rumtesten, aber ob das lösbar ist, weiss ich zur Zeit nicht wirklich.

**Comment by LongboatAline** [comment]
ich suche noch in welchem file das definiert wird (habe keine Ahnung von javascript, geschweige denn dart, angular, etc :)

**Comment by LongboatAline** [comment]
Nehme an, es ist `lib/src/forms/print-percentile.dart`  (habe mich von den generierten .js files etwas irritieren lassen). In den generierten .js files wird allerdings klar, dass rgb nach rgba konvertiert wird. evtl sorgt je nach darstellendem Programm die transparency komponente für ein "Umklappen" in die negativdarstellung? Weird.

**Comment by zreptil** [comment]
Ich denke auch, dass es an der Transparenz liegt.

**Comment by zreptil** [comment]
Besteht dieses Problem noch?

**Comment by zreptil** [comment]
Falls das Problem noch besteht, bitte erneut aufmachen.

**Comment by steve8x8** [comment]
I still see this. /beta/ site, downloaded to MacOSX 10.11, Preview shows purplish background of the GPD. (Page thumbnail at the left has the correct greenish colours.)

**Comment by zreptil** [comment]
This seems to be a problem with certain PDF viewers. If anybody can provide me with a way to reproduce this issue under Windows 10, i can take a look at it. But as long as this is only an issue on a special pdf-viewer on MacOSX i cannot do anything about it.

**Comment by steve8x8** [comment]
Your seem to be right, my Android device shows correct colours.
I haven't yet tried to print the file, either using the printer's raster engine or the one built-in MacOS but if I do I'll report here

**Comment by zreptil** [comment]
Ok, this seems to be a very limited problem on special programs that cannot handle transparency very well. I close this issue. If this occurs again, please open a new issue and tell me how to reproduce this issue.
