### ISSUE TITLE
PDFsplit: splittet bei 4Seiten/page nicht auf Seitengrenzen

### ISSUE THREAD

**Issue by LongboatAline** [zreptil/nightscout-reporter#11]
Wenn für Tages oder Wochengraphiken die Darstellung 4 pro physischer Seite gewählt wurde, wird die letzte Seite nicht ganz gefüllt, und das nachfolgende PDF beginnt dann mit einer entsprechend nur teilgefüllten Seite. 

![previous - nightscout reporter](https://user-images.githubusercontent.com/35570803/53251437-eed1f700-36bc-11e9-9b39-fdf54102d7d6.jpg)

![folgeseite - nightscout reporter](https://user-images.githubusercontent.com/35570803/53251421-e4176200-36bc-11e9-83d1-f67bf9e314cc.jpg)

**Comment by LongboatAline** [comment]
(Of course, the workaround is obvious - just call the uploader separately for the different graph types, it's nicer anyway to keep the graph type collated by pdf)

**Comment by zreptil** [comment]
Der Workaround ist nicht sehr sinnvoll ^^ Da baue ich lieber eine ordentliche Prüfung beim Seitenwechsel rein. Wegen der Probleme mit Dateigrössen der verschiedenen PDF-Plugins werde ich zwar die Seite trotzdem in so einem Fall mitten drin umbrechen lassen, aber die nächste Grafik wird dann wieder links oben platzert werden.

**Comment by zreptil** [comment]
Da waren noch Fehler in der Verarbeitung der PDF-Aufteilung. Mit der aktuellen Beta sollten diese behoben sein und auch keine doppelten Seiten mehr generiert werden. Der Seitenumbruch erfolgt nun auch zwischen den Seiten und nicht mehr innerhalb einer Seite, auch bei vier Grafiken pro Seite.
