### ISSUE TITLE
Multiple Datenquellen

### ISSUE THREAD

**Issue by LongboatAline** [zreptil/nightscout-reporter#13]
In der Übergangsphase zwischen 2 Sensoren ist es nicht außergewöhnlich, dass beide Systeme beabsichtigt oder unbeabsichtigt Messwerte liefern und in Nightscout hinterlegen. Im Idealfall sind sie sogar am Uploader unterscheidbar.

Interessanter Sonderfall ist, wenn jemand mehrere Systeme zum Vergleich trägt, und die Daten ebenfalls in dieselbe Datenbank kippt.

Ungünstig ist, wenn die Datenpunkte aller Sensoren dann mit einer fröhlichen Zickzacklinie verbunden werden :)

Einfachste Lösung ist vermutlich, nur Punkte zu verbinden, die a) denselben Uploader haben, und b) innerhalb eines einstellbaren? Noise-Grenzwertes liegen.

### neuer Sensor: Enlite 
(upload zu Nightscout via 600Series uploader, broadcast zu xDrip)
![201812 27_28enlite - unknown](https://user-images.githubusercontent.com/35570803/53286497-d1aa3080-376f-11e9-8f2b-aedab3af3f28.jpg)

### Tidepool view, dying G5 and Enlite simultaneously
(ich wollte den G5 Sensor noch eine Weile beobachten, um zu sehen ob in dem Zustand eine Chance besteht, dass die Dinger sich wieder fangen (Fazit: Nein))
![noise2sensors - tidepool](https://user-images.githubusercontent.com/35570803/53287146-6b75db80-3778-11e9-883e-0fb014685cb4.jpg)

### So sieht  Nightscout Reporter die Sache
![noise2sensors - nightscout reporter](https://user-images.githubusercontent.com/35570803/53287142-56994800-3778-11e9-9105-f1c194e4e6fc.jpg)

**Comment by zreptil** [comment]
Die einfachste Lösung schaut eigentlich so aus: kippe nicht aus zwei Systemen Daten in die gleiche Datenbank ^^ 

Ich muss mir das mal genauer anschauen. Vielleicht fällt mir was ein, wie man einen Filter reinbauen kann, ohne die normalen Benutzer zu nerven, die sowas nicht tun.

**Comment by LongboatAline** [comment]
Danke :) Ja, das Datenmodell ist da auch nicht optimal, aber immerhin führt es den uploader mit. 
Ich denke, dass eine Noise-Schwelle in vielerlei Hinsicht bereits helfen würde, da es bei Noise optisch einfacher ist, die scatter-Wolke zu interpretieren. Die Zickzacklinie suggeriert, dass der sgv so sehr schwankte, während bei der Punktwolke klar ist, dass die "Wahrheit" irgendwo dazwischen liegt

Der etwas aufwendigere Weg wäre, das glattzurechnen (z.b. mittels _unscented Kalman Filter_)

**Comment by zreptil** [comment]
Am Wochenende hatte ich auch einiges an Noise zu verkraften. Das Problem ist dabei nicht mal die Datenhaltung in Nightscout, sondern dass das Loop-System mit solchem Noise auch den Loop steuert. In so einem Fall ist es dann aber eher suboptimal, wenn man die Werte, die man als Noise zu erkennen glaubt, weil sie irgendwelche Grenzwerte verletzen im Ausdruck rausglättet. Da sieht man dann zum Beispiel, dass sehr viel Insulin abgegeben wurde, obwohl der Glukosewert eigentlich ok ist, weil der Wert von 400, den das Loop-System zur Steuerung verwendet, gar nicht auftaucht. 

Ich denke, man sollte dann eher die Daten in Nightscout selbst ändern, als im Ausdruck Werte ausserhalb willkürlich definierter Grenzwerte zu ignorieren. Ich habe bisher allerdings noch kein sinnvolles Programm zur Änderung der Nightscout Daten gefunden. Mit "sinnvoll" meine ich nicht das, was MongoDB bietet. Das erfordert einen Programmierer oder Datenbankspezialisten, um da irgendwas machen zu können.

**Comment by LongboatAline** [comment]
Noise ist sicherlich nicht sinnvoll ganz rauszunehmen, ich dachte daran, dass man bei Noise darauf verzichten könnte/sollte, die Punkte miteinander zu verbinden. 

Was ich rausnehmen würde (respektive testweise mal an drei Stellen (minimum, durchschnitt, graph) dilettantisch rausgepatcht habe) sind Werte unterhalb der Messschwelle des verwendeten Messsystems.
Wenn ein sterbender Sensor, wie gehabt, eine Stunde lang “5” flötet (Wobei mir noch nicht klar ist, wie die 5 da hineingekommen ist - der Loops sieht da nur ein "cgm unreachable"), ist das nichts, was in die Berechnungen eingehen sollte. In den Graphen ist strittig - da kann das zur Fehlersuche noch hilfreich sein. Daher der Wunsch das per Konfiguration ausblenden zu können :)

![nightscout-reporter low5 - unknown](https://user-images.githubusercontent.com/35570803/53339106-a6594a00-3905-11e9-9cd6-18ecb8c4ffaa.jpg)

Ich habe auch ein bisschen gesucht wie ich die DB aufräumen könnte, zumal ich auf ns10be nicht an die DB rankomme, sondern auf das API angewiseen bin. Gefunden habe ich bisher einen Hinweis auf `ns-dedupe-treatments` im [Gitter archiv von 2015](https://gitter.im/nightscout/intend-to-bolus/archives/2015/11/15)

**Comment by LongboatAline** [comment]
Wenn ein Wert konstant wiederholt wird, solange keine neuen Daten vorliegen sieht mir das nach einem Bug von AndroidAPS aus:

![bugnosgvflatline - unknown](https://user-images.githubusercontent.com/35570803/53339762-862a8a80-3907-11e9-8352-fb860a5cdf4b.jpg)

**Comment by LongboatAline** [comment]
> weil der Wert von 400, den das Loop-System zur Steuerung verwendet, gar nicht auftaucht.

Das sollte darüber, dass ab einer Noise Schwelle auf das `long average delta` zurückgegriffen wird, eigentlich verhindert werden?

Blöd ist, dass der G5 im native mode keinen noise mitliefert, und AndroidAPS meines Wissens nicht von selbst darauf kommt, springende Werte als Noise zu interpretieren. Da hilft dann nur `always use short average delta`.

**Comment by zreptil** [comment]
Theoretisch schon, praktisch an diesem Wochenende nicht. Das long average Delta hab ich schon lange drin und sowas ist bisher nicht vorgekommen. Ich habe inzwischen den MiaoMiao ausgetauscht und nun scheint es wieder zu funktionieren. Die Dinger halten wohl auch nicht ewig. 

Ich habe mir inzwischen Deine Daten angeschaut und da steht eine Eigenschaft "noise" in den Daten drin. Allerdings weiss ich bisher nicht, wie ich die interpretieren soll. Bei Deinen 5er Werten steht da immer -9999 drin, aber das steht bei anderen Werten auch teilweise drin. Das scheint also auch kein brauchbarer Wert zu sein, den ich sinnvoll auswerten kann.

**Comment by LongboatAline** [comment]
Jein. Gerade noch einmal nachgefragt:
*` > 0`: "echter Noise"
* `= 0`: kein Noise (das kann auch daran liegen, dass die Datenquelle keinen mitliefert, selbst wenn die Werte springen)
* `< 0`: Fehlerstatus
* `-9999` (4 Neunen): AAPS hat von xDrip keinen noise-Wert (also auch nicht 0)
* `-99999` (5 Neunen): xDrip, wenn der Sprung keinen "echten" noise darstellt = die ersten Werte nach einer Kalibrierung.

**Comment by zreptil** [comment]
Ist das noch ein Problem? Wenn ja, bitte erneut aufmachen.
