### ISSUE TITLE
Beginner question: error building

### ISSUE THREAD

**Issue by th122** [zreptil/nightscout-reporter#14]
`webdev build` steigt mir seit neuestem aus. liegt das an dem `pub upgrade`, das ich vorher gemacht habe, oder an etwas anderem? Dummerweise kenne ich weder Sprache noch Toolchain gut genug um zu wissen, wo ich da ansetzen muss.

```
17:44 $ webdev build
Creating build script, took 20152ms
[INFO] Reading cached asset graph completed, took 1.5s
[INFO] Checking for updates since last build completed, took 2.3s
[INFO] Running build completed, took 1.1s
[INFO] Caching finalized dependency graph completed, took 903ms
[SEVERE] build_web_compilers|entrypoint on web/main.dart (cached):
```

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'messages_es_ES.dart' deferred as messages_es_ES;` from nightscout_reporter|lib/messages/messages_all.dart at 15:1

**Comment by zreptil** [comment]
Sorry, da hatte ich vergessen, eine Datei hinzuzufügen. Jetzt sollte es gehen.

**Comment by th122** [comment]
Danke! geht prima :) 
Ich hatte inzwischen raus, dass bei mir ein upgrade auf Dart 2.2.0 durchgelaufen war, und hatte den schon im Verdacht...

**Comment by zreptil** [comment]
Das freut mich :) Ich verwende immer die aktuelle Dart Dev Version. Es kann also schon daran liegen, wenn Du Dart ohne Dev verwendest, aber bisher ist mir nicht aufgefallen, dass es da Probleme gibt. Ich glaube die sind ganz stabil mit ihren Versionen. Ich verwende die Dev, um eventuell kommende Änderungen im stable Release von Dart möglichst frühzeitig zu erkennen.

**Comment by gruoner** [comment]
Diesmal fehlt die messages_sk_SK.dart - kann ich den Eintrag aus der messages_all entsorgen oder muss man die noch ablegen?

**Comment by gruoner** [comment]
@K2S: du scheinst an der SK-Übersetzung gearbeitet zu haben; kannst du die messages_sk_SK.dart bitte noch einchecken?

**Comment by zreptil** [comment]
Ich habe gerade einiges eingecheckt. Da müssten alle Dateien dabei sein, die gefehlt haben. Wenn noch was fehlt, sagt Bescheid.

**Comment by gruoner** [comment]
hat sich erledigt
