### ISSUE TITLE
eCarbs als Summe statt Verteilung?

### ISSUE THREAD

**Issue by th122** [zreptil/nightscout-reporter#15]
Für den MD-report sehe ich mir gerade die eCarbs an. 
ich habe sie jetzt mal (Gipfel der Kreativität ;) auskommentiert, da sie in einem "normalen" Protokoll nicht berücksichtigt wären. 
Fuktioniert prima, aber sie werden noch aufsummiert, und erscheinen nun in ansonsten Carbfreien Zonen als Summe ohne Carb-graphik, da habe ich wohl noch etwas übersehen.

![nsr-ecarbs](https://user-images.githubusercontent.com/17241496/53596132-5dbcbd80-3b9f-11e9-98cc-31a3c4aff075.jpg)

Eine andere Möglichkeit wäre wahrscheinlich, sie aufzusummieren und in einen Square Bolus umzurubeln, aber das ist den Aufwand nicht wert, glaube ich. Unterdrücken reicht vermutlich, um den printout vorzeigen zu können ohne sich gleich als "macht komische Dinge" zu outen :)

(gehört im Prinzip zu #8)

**Comment by th122** [comment]
Hm. ohne Aufsummierung wird der Text auch mit dargestellt, ich finde nicht, wo ich den für die eCarbs deaktivieren kann. Hast Du einen Tipp für mich?

**Comment by zreptil** [comment]
Ich verstehe zwar nicht so wirklich, was Du da versuchst (vermutlich fehlen mir da noch Informationen dazu ^^), aber die eCarbs werden in jsonData.dart aus den Notizen der Treatments extrahiert.

**Comment by th122** [comment]
Ich versuche die eCarbs komplett zu unterdrücken, damit das ganze für den MD "normaler" aussieht.
Den Balken habe ich in print-daily-graphic.dart auskommentiert, damit bleibt nur der Text übrig.

Ansonsten probiere ich gerade aus, die Darstellung von Kommentaren auf Carb,- oder Boluseinträge zu begrenzen, um die ganzen automatischen Einträge auszublenden, aber zumindest mahlzeitenbezogene Kommentare drinzulassen. 

Das klappt schonmal, damit habe ich die aber auch bei den eCarbs, die ich unterdrücken will :)
![notesecarbs](https://user-images.githubusercontent.com/17241496/53601153-aed2ae80-3bab-11e9-9f70-39c3d13364a0.jpg)

**Comment by zreptil** [comment]
Wie ist denn der Stand mit der aktuellen Version? Brauchst Du da noch Anpassungen? Inzwischen ist mir klarer, dass man bei den Ärzten manchmal etwas vorsichtig sein muss, was man ihnen an Informationen zumutet ^^

**Comment by zreptil** [comment]
Wenn das noch ein Problem ist, bitte wieder aufmachen.
