### ISSUE TITLE
Combo (Dual) Bolus

### ISSUE THREAD

**Issue by th122** [zreptil/nightscout-reporter#16]
Nightscout is at least able to log a dual bolus, and I'm using that feature to log long-acting insulin as square bolus (Dual Bolus with no immediate component).
### Example (from Quantum):

```json
{
  "_id": {
    "$oid": "5c59c4082e74c0b0e99d234d"
  },
  "enteredBy": "th combo",
  "eventType": "Combo Bolus",
  "reason": "",
  "duration": 1080,
  "notes": "Lantus",
  "splitNow": "0",
  "splitExt": "100",
  "enteredinsulin": "12",
  "relative": 0.6666666666666667,
  "created_at": "2019-02-05T10:00:00.000Z"
}
```

### Use case: 
* temporary transition to ICT in less pump friendly environments (diving, sauna, ...)
* inform the loop of an additional injection of basal insulin
    * AndroidAPS will take note of that, and dose correctly
    * OpenAPS will only take insulin it has been administering itself into account, and ignore the entry AFAIK
* tally totals (TDD) correctly...

**Comment by zreptil** [comment]
What is the issue for nightscout reporter with this?

**Comment by th122** [comment]
Nightscout reporter seems to ignore a combo bolus - Unless I've missed something, it does't get calculated into the TDD, and it doesn't get displayed either. 

![nightscout-reportercombobolys](https://user-images.githubusercontent.com/17241496/53803906-64a05300-3f46-11e9-9ea4-c6d705f6eae7.jpg)

**Comment by zreptil** [comment]
You are right. The attribute "enteredinsulin" is ignored in treatments. I will change this so, that "enteredinsulin" is taken when no insulin is present in the treatmentdata. I think then the insulin should show up correctly.

**Comment by th122** [comment]
thanks, that'd be great. Ideally, I think, in the case of a bolus with a duration, the `relative` part would be applied to all hours that are affected - that way it would end up being accounted for at the correct time&date (I'm thinking of an extended bolus starting before midnight, for example).

There's two more things I've got in mind concerning TDD and basal rate, but I'll sort that into separate topics, so we can discuss (or junk ;) them separately.
