### ISSUE TITLE
BG reading shown as -1 in Protokoll

### ISSUE THREAD

**Issue by th122** [zreptil/nightscout-reporter#17]
Die Glukosespalte im Protokoll gefällt mir gut - sie ist wirklich hilfreich um die einzelnen Entscheidungen des Loops (oder des Diabetikers :) nachzuvollziehen. 
Aktuell (beta via zreptil.de) werden die bg Werte jedoch als "-1" dargestellt. In der Graphik hingegen werden die Punkte an die passende Stelle gesetzt.

![Kontrollmessung Sensorwechsel - Nightscout Reporter](https://user-images.githubusercontent.com/17241496/65166699-7d370d00-da41-11e9-8af6-a2eee6e5d132.jpg)
![2019-07-31 Quantum - Nightscout Reporter](https://user-images.githubusercontent.com/17241496/65167530-0bf85980-da43-11e9-98ab-bd8acb07266d.jpg)

... und immer wieder Danke für diesen tollen Reportgenerator!

**Comment by zreptil** [comment]
Das ist mir bei meinen Daten bisher noch nicht aufgefallen. Wenn Du mir den Link zu Deinen Daten zukommen lässt, dann schaue ich, wieso das so ausgegeben wird.

**Comment by th122** [comment]
Danke - habe ich Dir die Zugänge zu Quantum/Tantum/Erratum geschickt. Das Beispiel ist von Quantum.

Bei länger zurückliegenden Zeitspannen wirst Du auch auf BG Einträge stoßen, die das Messgerät via BT an xDrip gesendet hat, bei neueren (Telephon umgeflasht und noch nicht wieder gekoppelt) nur auf manuell eingegebene. Kann natürlich sein, dass die unterschiedlich dargestellt werden. Juli müsste noch vor dem Telephon-GAU gewesen sein.

**Comment by th122** [comment]
Gerade getestet: Messung auf Quantum um 13:01 wurde manuell in xDrip eingegeben, erscheint als -1

**Comment by zreptil** [comment]
Ich habe es gerade auf meiner lokalen Umgebung behoben, mit Deinen Daten getestet und für gut befunden :) Mit dem nächsten Update werden die blutigen Werte wieder korrekt angezeigt.

**Comment by th122** [comment]
Danke!
Ich renne gerade dem nächsten Problem nach, aber das hat nichts mit dem Reporter zu tun (Du kannst es sehen, wenn Du Dir gestern ansiehst, darüber ist es mir zumindest aufgefallen :)

**Comment by zreptil** [comment]
Behoben in Version 1.3.5
