### ISSUE TITLE
TBR wird bei Tageswechsel als beendet angesehen

### ISSUE THREAD

**Issue by th122** [zreptil/nightscout-reporter#18]
Bereits in #8 angespeochen, und immer noch aktuell:
Der Reporter geht davon aus, dass eine TBR um Mitternacht endet, und ab Mitternacht die in Nightscout hinterlegte Basalrate weiterläuft (oder inzwischen sogar die "echte" aus der Auswertung der Profilwechsel?.
Wenn die abgegebene TBR vom Profil in Nightscout abweicht, ist damit bis zur nächsten TBR definitiv ein Fehler drin, der auch in die Summenberechnung des Tages einfließt.

Interessanterweise ist die Größe des Fehlers je nach Reporter Version unterschiedlich. Im Vergleich `1.38g` versus `1.3.4`. Ich nehme an, das liegt an der inzwischen deutlich bessere Erkennung der Profilwechsel?

![2019-07-31 Quantum 1 38g - Nightscout Reporter](https://user-images.githubusercontent.com/17241496/65167530-0bf85980-da43-11e9-98ab-bd8acb07266d.jpg)
![2019-07-31 Quantum 1 3 4 - Nightscout Reporter](https://user-images.githubusercontent.com/17241496/65169703-5f6ca680-da47-11e9-8bb9-e03a033778be.jpg)

![Tageswechsel 2019-07-31 - Nightscout Reporter](https://user-images.githubusercontent.com/17241496/65169717-67c4e180-da47-11e9-8bbb-fce51e70325e.jpg)

Die gesetzte Basalrate aus dem Log von AAPS:
```
23:53:36.730 [Thread-7731] DEBUG [RuffyScripter.runCommand():325]: Command result: CommandResult{success=true, state=PumpState{timestamp=1564523616728, pumpTime=1564523520000, menu='MAIN_MENU', suspended=false, tbrActive=true, tbrPercent=0, basalRate=0.0, tbrRemainingDuration=120, activeAlert=null, batteryState=0, insulinState=0, activeBasalProfileNumber=0, unsafeUsageDetected=0}, history=null, basalProfile=null, forwardedWarnings='[]'}
23:53:36.731 [Thread-7731] DEBUG [RuffyScripter.runCommand():326]: Connect: 0s, execution: 6s
23:53:36.732 [Thread-7731] DEBUG [ComboPlugin.runCommand():907]: Finished activity: Setting TBR (0% / 120 min)
23:53:36.762 [Thread-7731] DEBUG [DatabaseHelper.createOrUpdate():964]: TEMPBASAL: New record from: USER TemporaryBasal{date=1564523616000, date=7/30/19 23:53, isValid=true, pumpId=0, _id=null, percentRate=0, absoluteRate=0.0, durationInMinutes=120, isAbsolute=true, isFakeExtended=false, netExtendedRate=0.0}
23:53:36.767 [pool-2-thread-1] DEBUG [DatabaseHelper.lambda$scheduleTemporaryBasalChange$2$DatabaseHelper():1018]: Firing EventTempBasalChange
23:53:36.768 [pool-2-thread-1] DEBUG [TreatmentsPlugin.onStatusEvent():328]: EventReloadTempBasalData
23:53:36.778 [Thread-7731] DEBUG [DbLogger.dbAdd():28]: DBADD dbAdd 1 receivers {"eventType":"Temp Basal","duration":120,"absolute":0,"rate":0,"created_at":"2019-07-30T21:53:36Z","enteredBy":"openaps:\/\/AndroidAPS"}
23:53:36.780 [NSClientServiceHandler] DEBUG [UploadQueue.lambda$add$0$UploadQueue():47]: QUEUE adding: {"eventType":"Temp Basal","duration":120,"absolute":0,"rate":0,"created_at":"2019-07-30T21:53:36Z","enteredBy":"openaps:\/\/AndroidAPS","NSCLIENT_ID":1564523616780}
23:53:36.794 [NSClientServiceHandler] DEBUG [NSClientPlugin.onStatusEvent():160]: DBADD treatments Sent 1564523616780
23:53:36.795 [Thread-7731] DEBUG [CommandTempBasalAbsolute.execute():37]: setTempBasalAbsolute rate: 0.0 durationInMinutes: 120 success: true enacted: true
```
Durch zurücklesen aus Nightscout bestätigt:
```
23:53:36.844 [IntentService[DataService]] DEBUG [DatabaseHelper.createOrUpdate():926]: TEMPBASAL: Updating record by date from: NIGHTSCOUT TemporaryBasal{date=1564523616000, date=7/30/19 23:53, isValid=true, pumpId=0, _id=1564523616780, percentRate=0, absoluteRate=0.0, durationInMinutes=120, isAbsolute=true, isFakeExtended=false, netExtendedRate=0.0}
23:53:36.845 [pool-2-thread-1] DEBUG [DatabaseHelper.lambda$scheduleTemporaryBasalChange$2$DatabaseHelper():1018]: Firing EventTempBasalChange
```
Was auch der Blick auf die Pumpe bestätigt:
```
23:53:39.843 [Binder:6969_2] DEBUG [RuffyScripter$1.rtDisplayHandleMenu():100]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={TBR=0.0, INSULIN_STATE=0, WARANTY=false, BATTERY_STATE=0, BASAL_SELECTED=1, BASAL_RATE=0.0, TIME=23:52, LOCK_STATE=0, DEBUG_TIMING=0.02, RUNTIME=2:00}}
```

_See also @LongboatAline in https://github.com/zreptil/nightscout-reporter/issues/8#issuecomment-466360274_

**Comment by quizzmaster** [comment]
Das Problem ist in der Tat noch vorhanden. Ich konnte es mit meinen Daten verifizieren.

**Comment by zreptil** [comment]
Das hatte ich in der Tat aus den Augen verloren. Die unterschiedlichen Werte haben sicherlich mit der verbesserten Profilverarbeitung zu tun. Ich muss mir das noch genauer anschauen. Das Problem dürfte die Aufteilung der Periode in Tage sein. Die Daten werden dann um 0 Uhr abgeschnitten, was tatsächlich ziemlich suboptimal ist. Ich werde schauen, ob mir dazu eine Lösung einfällt (wovon ich ausgehe ^^).

**Comment by zreptil** [comment]
Das wird mit Version 1.3.5 behoben.

**Comment by th122** [comment]
Oh fantastisch, ich Danke Dir! Das kommt gerade prima, ich habe gerade die Daten zusammengesucht um ein "Loop Video" der wear Komponente mit dem passenden Tag zu hinterlegen, und da sahen #17 und #18 doof aus :)

**Comment by zreptil** [comment]
Das ist gut :) Auf der Beta ist es drauf, mit der Live warte ich noch. Es könnte sein, dass das noch nicht so ganz passt. Immerhin wird der Tageswechsel jetzt korrekt eingebaut.
