### ISSUE TITLE
more insuline types support

### ISSUE THREAD

**Issue by k2s** [zreptil/nightscout-reporter#23]
There is a work in progress to add more insuline types to xDrip and Nightscout.
The work and discussion happens in [pull request #973](https://github.com/NightscoutFoundation/xDrip/pull/973).

Would you be willing to use the extended JSON structure that will be uploaded to NS by this functionality in your great reports ?

Breaking down the amount of long, short, rapid insulin based on this information would be interesting.

I am using the pull request already and uploading to NS and could share with you if you need that for testing/example data.

**Comment by k2s** [comment]
* the time when insuline types will be merged to xDrop master comes closer (https://github.com/NightscoutFoundation/xDrip/pull/1080)
* I am storing data to my NS already with this latest pull request
  * I will contact you on Gitter to provide you with link to my data
* will try to identify on what places in PDF I would like to see the informatin about insuline type

**Comment by gruoner** [comment]
ich versuche gerade die neuen Strukturen in meine Reports einzubauen aber ich krieg den webdev serve nicht wirklich ans laufen (new to AngularDart) und im generieren Javascript mag ich nicht nach dem Fehler suchen..... hat es da eine anständige IDE mit der man das ganze Debuggen kann?

**Comment by zreptil** [comment]
Als IDE für Anguilardart verwende ich WebStorm. Für das Debugging nehme ich bisher in Chrome immer die DevTools. In WebStorm soll es aber seit ein oder zwei Versionen die Möglichkeit geben, das direkt da drin zu debuggen. Das kann ich allerdings bisher weder bestätigen noch dementieren.

**Comment by gruoner** [comment]
Danke für die schnelle Antwort, genau auf den setup wollte ich auch hinaus. Aber wie krieg ich den Chrome mit DevTools dazu den DartCode zu debuggen? Wenn ich den geänderten DartCode mit webdev serve starte, kann ich den nightscout-reporter nicht direkt auf "localhost:8080" ansprechen - chrome scheint da keinen index.html etc. zu finden......

**Comment by zreptil** [comment]
Ich starte das immer mit dem Befehl:

C:\Program Files\Dart\dart-sdk\bin\pub.bat global run webdev serve web:3001

im Verzeichnis des Projektdirectories. Dann kann ich das im Browser unter localhost:3001 aufrufen. Dort habe ich dann in den DevTools auf der Source Seite alle Sourcen inklusive Breakpoints zur Verfügung.

**Comment by gruoner** [comment]
kaum macht man's richtig, schon funktionert's.... DANKE
