### ISSUE TITLE
Combo Bolus not shown

### ISSUE THREAD

**Issue by marc-gaub** [zreptil/nightscout-reporter#25]
Hello,
I cannot see the combo bolus in the reports. I entered a combo bolus of 17 units, 10 units immediately, and 7 units over 8 hours. In nightscout, it's reported correctly, but it's missing in the reports. See attached printscreen.
Thank you for your support
<img width="857" alt="Screenshot 2019-11-01 at 10 41 05" src="https://user-images.githubusercontent.com/46347773/68016624-3b7ec080-fc95-11e9-8f13-bbd566aa6e3c.png">
<img width="216" alt="Screenshot 2019-11-01 at 10 42 47" src="https://user-images.githubusercontent.com/46347773/68016635-3faade00-fc95-11e9-9f42-96792a24c813.png">

**Comment by zreptil** [comment]
I think, meanwhile this should be implemented. If it still is an issue, please reopen it.
