### ISSUE TITLE
Bloody measurements listed as "-1" on server (still running @1.3.4)

### ISSUE THREAD

**Issue by steve8x8** [zreptil/nightscout-reporter#26]
I'm uploading BG (finger prick) values to Nightscout through xDrip (type:mbg), but those show up in the report ("Protokoll") as "-1". CGM values are OK, as are the weekly curves  ("Wochengrafik", with BG points at the correct places). What am I missing?

**Comment by steve8x8** [comment]
Update: I just found #17 which reports that the issue has been fixed in version 1.3.5 (in September). Unfortunately, the web service is still running at 1.3.4. Modifying the issue title...

**Comment by zreptil** [comment]
This is fixed in the beta at https://nightscout-reporter.zreptil.de/beta. I want to bring the beta to the live version, but before this, I have to take a look if it is stable enough to do so.

**Comment by steve8x8** [comment]
Indeed, 1.3.6ßf shows "real" numbers. Thanks.
(Minor nitpick: red BG measurements on red "low" background are illegible.)
