### ISSUE TITLE
Recommendations From the International Consensus on Time in Range

### ISSUE THREAD

**Issue by k2s** [zreptil/nightscout-reporter#28]
It would be great if we would have this type of evaluation in reporter:
https://care.diabetesjournals.org/content/early/2019/06/07/dci19-0028.full-text.pdf

**Comment by zreptil** [comment]
Do you mean the AGP-Report? Everything on it can be seen in different PDFs in Nightscout Reporter. Is there something that NR doesn't evaluate?

I think, it would be possible to create a PDF that looks like page 7 of the link. Is this relevant for many people or is this just for some people working in laboratories?

I can create such a PDF, but it is time consuming, so i would be glad, if you could give me feedback, if this is really a thing that would be useful for many people.

**Comment by zreptil** [comment]
Since there is no feedback to this issue, i close it. If it is an issue again, please open a new one.
