### ISSUE TITLE
Stündliche Statistik bei fehlenden Daten

### ISSUE THREAD

**Issue by nshtg** [zreptil/nightscout-reporter#30]
Hallo Andi,

beim experimentieren sind mir zwei kleine Bugs aufgefallen. Bilder sagen bekannterlicherweise mehr:

Der fragliche Tag (in der Lücke wurde ein neuer Sensor gestartet und nachträglich ein bisschen noisy data entfernt)
![ArcoLinux_2020-01-03_21-59-33](https://user-images.githubusercontent.com/5219415/71749011-8de68400-2e74-11ea-91a5-02199ed5a87f.png)

Die "Stündliche Statistik"
![ArcoLinux_2020-01-03_21-59-58](https://user-images.githubusercontent.com/5219415/71749047-aa82bc00-2e74-11ea-9b20-59c8ae5c190b.png)

Die Auswertung auf Seite 1 (bei den Standardgrenzwerten ist das Kästchen für Low zu groß)
![ArcoLinux_2020-01-03_22-00-17](https://user-images.githubusercontent.com/5219415/71749101-cab27b00-2e74-11ea-8d9f-ac63cceb008a.png)

Zugang zu meinem NS müsstest du noch haben.

Viele Grüße!

**Comment by zreptil** [comment]
Bei der stündlichen Statistik sind die Werte natürlich suboptimal. Das werde ich korrigieren. Die Höhe der Balken in der Analyseseite ist natürlich auch nicht schön. Da schau ich nach, was los ist und korrigiere das auch.

Die Tagesgrafik schaut aber ok aus. Oder habe ich da ein Problem übersehen?

**Comment by nshtg** [comment]
Nein, die Tagesgrafik war nur um zu verdeutlichen wie der Tag an sich aussieht.

**Comment by zreptil** [comment]
Ok, prima :) Dann kümmere ich mich um die offensichtlichen Fehler :) 👍

**Comment by zreptil** [comment]
Wenn Du mir noch sagst, wer Du bist, kann ich mir die Daten anschauen :) Leider bringen mir Hinweise auf vergangene Probleme in der Hinsicht nichts, weil ich inzwischen viel zu viele Benutzer habe, um da den Überblick behalten zu können, wenn sie verschiedene Aliase verwenden ^^ Du kannst mir gerne eine Mail an andi@zreptil.de schicken.

**Comment by nshtg** [comment]
Ich close dann mal, danke für die schnellen Fixes!

**Comment by zreptil** [comment]
Freut mich, dass die Lösung passt :)
