### ISSUE TITLE
Bug: Daily Graph - CGP - Pentagon - CV% is set to the average for the whole period

### ISSUE THREAD

**Issue by cfaagaard** [zreptil/nightscout-reporter#32]
The CV% in the pentagon on the "daily graph"-page is showing the average for the whole period, not the daily CV% as shown correct int "Daily Statistics"-page.

Example: 
Running a report for November.
On the 11/02/2019 the CV% value in the "Daily statics" is 32.9, but on the "Daily Graph" the value is 50%. Which is incorrect. This should be 32.9 as well. In fact, for all the dates in the "Daily Graph"-pages the CV% is 50%.
And the average CV% for the whole period is 50% as shown in the "Daily Statics".
![image](https://user-images.githubusercontent.com/25353502/71831138-9b844f80-30a8-11ea-87cb-f9201f83c39e.png)
![image](https://user-images.githubusercontent.com/25353502/71831213-b8208780-30a8-11ea-808f-cd54438a4c69.png)

**Comment by steve8x8** [comment]
Ah, something similar seems to happen with the avg BG (#33)...

**Comment by zreptil** [comment]
Good information. Thank you for finding this bug :) It will be fixed in Version 1.3.8

**Comment by cfaagaard** [comment]
testing version 1.3.8: the pentagon graph is still showing the wrong value. 
The text shows 61% but the graph is showing the average for the periode 42%.

![image](https://user-images.githubusercontent.com/25353502/72202257-8408e600-345d-11ea-819e-4ea55fef4c6e.png)

**Comment by cfaagaard** [comment]
Same thing (I think) with the ToR. It shows the whole periods value 516 minutes, it is not showing the total of minutes for this day. Both in graph and text.
![image](https://user-images.githubusercontent.com/25353502/72202356-afd89b80-345e-11ea-98c8-58f76db7cf4e.png)

**Comment by zreptil** [comment]
Great findings, thank you. :) It will be fixed in Version 1.3.9.

**Comment by cfaagaard** [comment]
And thank you for a great tool. I have been promoting your tool in the Danish Loop community, so expect some more Danish users :-)

**Comment by zreptil** [comment]
I am glad to hear this :) If you need danish language in Nightscout Reporter let me know. I will add this language to crowdin. But first i need to know if it is better to have english or german as baselanguage for the translators.

**Comment by cfaagaard** [comment]
I prefer the English version. :-) But I will let you know if there is a need for a Danish translation. Thank you.
