### ISSUE TITLE
CGP uses wrong numbers in description if mmol/L

### ISSUE THREAD

**Issue by steve8x8** [zreptil/nightscout-reporter#33]
"Die Zeit pro Tag in Minuten, in denen die Werte ausserhalb des Bereichs 70 mmol/L bis 180 mmol/L liegen." - this (and several lines below) uses the lower and upper limit values of mg/dL measurements. The "average glucose" axis is correctly labelled, but shows a value (in the text, 115 "mmol/L", ~ 6.4 "real" mmol/L) different from the title page (9.2 mmol/L).
This is not my own Nightscout, I guess I'm not entitled to share the URL right now.

**Comment by steve8x8** [comment]
Re different averages: this seems to happen only if there are large gaps in the recording. Going from 3 months to a week eliminates the difference. Is the average calculated in multiple places?

**Comment by cfaagaard** [comment]
I experience the same thing 
![image](https://user-images.githubusercontent.com/25353502/71969057-3e9eab80-3206-11ea-816b-7dbb5de101dd.png)

**Comment by zreptil** [comment]
the wrong values for mmol in the info area of the cgp will be fixed in version 1.3.8.
