### ISSUE TITLE
Duplicated finger bg points in mmol/L mode

### ISSUE THREAD

**Issue by steve8x8** [zreptil/nightscout-reporter#34]
![Screen Shot 2020-01-07 at 16 33 28](https://user-images.githubusercontent.com/11962538/71909015-5c6d0180-316f-11ea-8440-5cc9efa278cc.png)

The corresponding JSON records read as follows (redacted):
```
{"_id":"x","created_at":"2020-01-01T15:00:48.000Z","enteredBy":"medtronic-600://x-x","eventType":"BG Check","glucose":10,"glucoseType":"Finger","key600":"x","notes":"Faktor: 7.73 Ziel: 10,0 mmol/L (30s)","pumpMAC600":"x","units":"mmol","utcOffset":0,"carbs":null,"insulin":null},
{"_id":"x","created_at":"2020-01-01T09:35:34.000Z","enteredBy":"medtronic-600://x-x","eventType":"BG Check","glucose":11.9,"glucoseType":"Finger","key600":"x","notes":"Faktor: 6.64 Ziel: 11,9 mmol/L (21s)","pumpMAC600":"x","units":"mmol","utcOffset":0,"carbs":null,"insulin":null},
```
Values are in mmol/L, and "units" is correctly set. The red values shown at the bottom, corresponding to the low half of the dots, are 1/18 of the real values. Nightscout gets them right. (I have no idea what the "Factor" notes are good for.)

**Comment by zreptil** [comment]
Could you provide me with the link to your data? I need to reproduce this error in my development environment to solve the problem. My bloody values are displayed correct and only once. If you don't want to share your link public, just send it to andi@zreptil.de

**Comment by steve8x8** [comment]
done...
