### ISSUE TITLE
Bug?: Daily Statitics - Totals are wrong

### ISSUE THREAD

**Issue by cfaagaard** [zreptil/nightscout-reporter#35]
How are the totals in the Daily Statistics calculated? I have tried make a simple average and weighted average (based on the number of "values") and neither match the numbers in the report. 
![image](https://user-images.githubusercontent.com/25353502/72418958-24bc1600-377c-11ea-86f6-36b46add37ad.png)
For example if you look at the CV% in the picture. Total for 3 days is 46,2.
A simple average of the numbers: 31.4
A weighted average of the numbers: 35.5

Same thing with SDev. Total for 3 days is 3.0
A simple average of the numbers: 2.1
A weighted average of the numbers: 2.4

**Comment by quizzmaster** [comment]
These are not averages but the values for the whole period. You simply can't just build an average :wink:

**Comment by cfaagaard** [comment]
aaaahhhh. Thank you. I was going crazy about this. :-)
I will close the issue.

**Comment by zreptil** [comment]
@quizzmaster is right. The values are not calculated by summing the columns, but by using all values within the period and calculating the averages. So the values are really correct, but you cannot calculate them by using the values in the table. This will almost every time give another value.
