### ISSUE TITLE
Fehler bei Generierung der "Basalrate"

### ISSUE THREAD

**Issue by nshtg** [zreptil/nightscout-reporter#36]
Hallo Andi,

mir ist mal wieder was in der aktuellen Beta aufgefallen; siehe Screenshot mit Pfeilmarkierungen:

<img width="1109" alt="Screenshot 2020-01-20 at 09 00 37" src="https://user-images.githubusercontent.com/5219415/72708697-95d84080-3b63-11ea-8236-c286611f1861.png">

Zeitraum ist der 01.01.20 - 20.01.20
Einstellungen für Basalrate:
<img width="327" alt="Screenshot 2020-01-20 at 09 03 07" src="https://user-images.githubusercontent.com/5219415/72708753-b1dbe200-3b63-11ea-9dff-3ee34b82bbb6.png">

Meinen Zugang hast du noch von dem letzten Bugreport.

Viele Grüße

**Comment by zreptil** [comment]
Ich denke, ich habe das in der Beta inzwischen behoben. Hat eine Weile gedauert, aber es müsste jetzt besser passen, was da ausgegeben wird.

**Comment by nshtg** [comment]
Ist behoben, danke!
