### ISSUE TITLE
options for glucose Pentagon 

### ISSUE THREAD

**Issue by paulobenoit** [zreptil/nightscout-reporter#38]
Hello, is there a way to get a new option for the glucose Pentagon in order to be able to use our own target area instead of the standard Target Area to analyze the ToR axis?

**Comment by zreptil** [comment]
This was up to now no option, but I will add this option to the different PDFs where CGP can be created.  It will first be available in the beta. Maybe tomorrow or in the next days.

**Comment by paulobenoit** [comment]
I just tried this morning, the option is available for the CGP tile (French translation is missing) , but the text in the report still shows the standard target area. Then I don't know if the own target area is used correctly or not. Even if I changed the period or the target areas, the tor always shows the same value (373 min/day for me)
All the values of the CGP tile do not change even if I change the analyzed period (1 week, 2weeks, 1 month) and the target area

**Comment by zreptil** [comment]
If you let me know the url to your datas, i can take a look, why it doesn't work for you. I tried it with my data and everything is fine. You have to use https://nightscout-reporter.zreptil.de/beta/ fo this to work.

**Comment by paulobenoit** [comment]
Problem is solved on beta version. Thanks! :)

PS: French translations are up to date on Crowdin ;)

**Comment by zreptil** [comment]
Moved the option to use different targetareas to a new pdf-dialog. This is done with version 1.4, which is meanwhile live.
