### ISSUE TITLE
Zugriff auf http://server.local.domain:port ?

### ISSUE THREAD

**Issue by steve8x8** [zreptil/nightscout-reporter#39]
Hallo,
ich versuche - da ich noch keinen nginx zum Laufen bekommen habe - den NSRep direkt auf http:// zugreifen zu lassen. Das wird mir verweigert, der Server sei nicht erreichbar. Im Browser kann ich NS öffnen, "cors" ist im env gesetzt, /proc/$pid/environ hat es in ENABLE, - aber an irgendetwas hakt es.
Im syslog des NS-Servers finde ich keine zu den Zugriffsversuchen des NSRep passenden Zeilen, für die normalen Webzugriffe schon :(
Wie kann ich das debuggen, würde sich etwas ändern, wenn ich eine NSRep-Instanz lokal installierte?

**Comment by zreptil** [comment]
Nightscout Reporter verwendet ganz normale HTTP-Requests. Die sollten sowohl auf https als auch auf http funktionieren, solange die URL über den Browser in dem er läuft erreichbar ist und "cors" dort aktivert ist. Ob Nightscout Reporter drauf kommt, kannst Du prüfen, indem Du die status.json abfragst. Die kriegst Du über die URL [Nightscout Link]/api/v1/status,json. Da muss dann unter ENABLE cors stehen. Wenn das gegeben ist, sollte der Zugriff funktionieren. 

Ich debugge Nightscout Reporter immer mit den Development Tools von Chrome. Chrome ist auch der einzige Browser, in dem das funktioniert, weil alle anderen mit Dart nicht klar kommen. So richtig kann ich das allerdings nur in Webstorm debuggen. Das Deployment beinhaltet keine Sourcedateien, sondern nur gepackte Javascript Dateien.
