### ISSUE TITLE
Größere Zeiträume (z.B. 3M) mit Tagesstunden => HTTP 500 Error

### ISSUE THREAD

**Issue by nshtg** [zreptil/nightscout-reporter#40]
Hallo Andi,

ich finde das Tagesstundenfeature super! Allerdings ist mir aufgefallen, dass bei größeren Zeiträumen (1 Monat geht, 3 Monate nicht) beim benutzen des Features ein HTTP 500 Internal Server Error generiert wird. Ohne Tagesstunden funktioniert es.

Letzte mal probiert vor 1-2 Minuten (Mon, 16 Mar 2020 17:07:22 +0000 ist "jetzt").

VG

**Comment by zreptil** [comment]
Das liegt normalerweise daran, dass der Browser nicht in der Lage ist, die Anzahl an Blättern auszugeben, die da angefordert werden. Schiebe den Schieberegler in den Einstellungen weiter  nach links, dann sollte es irgendwann funktionieren.

**Comment by zreptil** [comment]
Hallo nshtg,

das liegt nach wie vor daran, dass es zu viele Daten sind, die Du da auf einmal ausgeben willst. Wenn Du entweder weniger Formulare auf einmal verwendest oder den Bereich verringerst, funktioniert es problemlos. Der Schieberegler ist nur eine Option, um der Datenflut Herr zu werden. 

Ich habe das mit einigen Änderungen ausprobiert (andere Optionen, weniger Tage, weniger Formulare) und es gelingt oft, dass das erzeugt wird, aber manchmal ist es einfach zu viel, was dem Browser abverlangt wird. Die Datenmengen, die bei drei Monaten einfliessen sind gewaltig. Und die Optionen in der Tagesgrafik können auch extrem viele Daten pro PDF-Seite verursachen. Wenn dann noch wie bei Dir zwei Tage pro Seite ausgegeben werden, kann das den Rechner schon ins Grübeln bringen.

Das ist etwas, woran ich nichts ändern kann. Die Erzeugung des PDFs funktioniert mit Deinen Daten einwandfrei. Das Problem ist die Grösse des PDFs und die Befüllung einzelner Seiten. 

Ich habe auch einen Extremversuch gemacht: Deine Einstellungen genauso beibehalten wie Du sie hast und nur folgendes geändert: Alle Formulare ausgewählt und in den Optionen der Tagesgrafik "Grafiken pro Seite" auf "Eine" gestellt. Das erzeugt mir 5 PDFs, die ich alle problemlos öffnen kann.

Das aktuelle Problem bei Dir sind die zwei Grafiken pro Seite. Damit bringst Du den PDF Erzeuger bei diesem Zeitraum ans Limit.
