### ISSUE TITLE
Standardabweichung: Werte sind zu gross

### ISSUE THREAD

**Issue by kameamea** [zreptil/nightscout-reporter#41]
ich bekomme StdAbw-Werte, die so hoch sind, dass sie mathematisch keinen Sinn mehr ergeben.
Der Code für die Berechnung in jsonData.dart sieht korrekt aus, daher vermute ich, dass es die NaN-Werte (also Zeiten, wo keine Messwerte vom CGM vorhanden sind) sind, die hier für einen falschen Gesamtwert sorgen.

Im beiligenden Protokoll sind folgende Dinge "seltsam":

[document(1).pdf](https://github.com/zreptil/nightscout-reporter/files/4383720/document.1.pdf)

Es gibt 507 Messungen, obwohl das Dexcom G6 meines Wissens nur alle 5 Minuten misst
In der Tagesstatistik stehen 229 Messwerte, das "passt" etwa zu den Lücken  in der Tagesgrafik.
Bei der Auswertung ist die Standardabweichung 66,9
In der Tagesstatistik dann 84.6
Auch min/max/Mittelwert passen nur in etwa zueinander

Aber überall ist die Stdabw. deutlich höher als math. Sinn ergibt, ich schätze aufgrund der Kurve, dass sie höchstens bei 40 liegen dürfte. 66.9 wäre sie, wenn der halbe Tag 140+66.9 = 207 und der andere halbe Tag 140-66.9 = 73 wäre, Beide Werte werden kaum je überschritten.

Auch an anderen Tagen sehe ich ähnliches Verhalten

**Comment by zreptil** [comment]
Leider kann ich aus den Angaben nicht wirklich entnehmen, was da schief läuft. Wenn Du mir den Link zu Deinen Daten zukommen lässt, kann ich mal schauen, ob ich da etwas entdecken kann, was die Abweichungen erklären kann (doppelte Datensätze, NaN-Werte oder sonst etwas).

**Comment by gruoner** [comment]
ich hab ähnliche Effekte an Tagen, wo über einen längeren Zeitraum (ein paar Stunden z.B. bei Sensorwechsel und Calibrierungsphase) keine CGM Daten registriert werden

**Comment by zreptil** [comment]
Bei der Berechnung der Analysewerte wurde noch der Vortag mit reingerechnet. Daher kamen die Abweichungen. Ausserdem wurden noch unsinnige Werte wie -1 teilweise mit in die Berechnung übernommen. Das ist in Version 1.4.3 korrigiert.
