### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by pinmike** [zreptil/nightscout-reporter#42]
Hi, this app looks great and very useful as I need to give reports to my doctor somehow and it's not easy to get them from Nightscout. I am stuck on how to get this app working from the source code on github though. Do you have any summary instructions? Thank you!

**Comment by zreptil** [comment]
Hi Mike,
you can use it here: https://nightscout-reporter.zreptil.de/

All you need to do is to put the link to your nightscout data in the settings and you can create the reports.

If you want to compile it yourself, you should know how to setup an IDE for dart projects. I use WebStorm from JetBrains. I don't have a tutorial for setting up the project, sorry. 

The files for letting it run on your local machine are packed in the file https://nightscout-reporter.zreptil.de/nightscout-reporter_local.zip

If you really want to compile it by yourself, you need to setup the development environment on your machine and have programming skills, that should make it easy to do so.

**Comment by pinmike** [comment]
Hi, thanks a lot for replying!

I've already got your online app working, had to enable cors on my heroku then all working fine. I wanted to just run my own local fork of it in case your website ever went down and I need the reports.

I'll try the zip link you provided, otherwise I'll take a look at webstorm/dart projects. I'm a PHP/Python/Java/Scala developer, not worked on dart before but at least knowing that info might be enough to get me started and sure there are guides online for setting up dart projects in webstorm (normally use Sublime, Vi or JetBrains IntelliJ).

Thanks a lot for the help!

**Comment by zreptil** [comment]
When you are used to IntelliJ, WebStorm will be easy enough for you. All projectfiles are in the github-repository. I think it should work, if you just load it as project in WebStorm. :)
