### ISSUE TITLE
Sensor Wechsel werden im xDrip offensichtlich nicht als "sensor change" sondern als "Sensor Start" registriert

### ISSUE THREAD

**Issue by gruoner** [zreptil/nightscout-reporter#45]
Einen "Sensor Stop" scheint es aber nicht zu geben :-)

--> passt du das im Mainstream NSR an oder soll ich das in meinem eigenen Code einbauen?
print-daily-graphic.dart um die Zeile 677 rum

**Comment by zreptil** [comment]
Danke für den Hinweis. Das baue ich so um, dass es zentraler gelöst wird. Die Abfrage in einem Formular ist da eher suboptimal. Ich passe es an und tu es ins Repository.

**Comment by gruoner** [comment]
Danke

**Comment by gruoner** [comment]
habs in meine Feature Branches übernommen und es funktioniert alles....
Das ging ja wirklich schnell.... :+1:
