### ISSUE TITLE
Treatments des Vortags werden in den täglichen Diagrammen nicht korrekt übertragen

### ISSUE THREAD

**Issue by gruoner** [zreptil/nightscout-reporter#46]
![image](https://user-images.githubusercontent.com/51212163/94485681-97700300-01de-11eb-946a-be4a50a6457a.png)

scheinbar startet jeder Tag mit einer Injektion um 0:00 - egal wie lange die Injektion am Vortag schon gelaufen ist.
Die Aktivitätskurve (ich hab sie hier in dunkelblau eingezeichnet) startet immer um Mitternacht und geht die obligatorischen 180min.

Selbstverständlich ist das nicht korrekt so und ich hab den Fehler bis zur DayData.iob im json_data zurückverfolgt:
![image](https://user-images.githubusercontent.com/51212163/94486198-575d5000-01df-11eb-8a96-44585657b7b0.png)
Dort scheint ein virtueller Treatment mit dem Injektionszeitpunkt 0:00 und der Höhe des "Rest-IOB" vom Vortag angelegt und dann durchkalkuliert zu werden. Die Kalkulationsfunktion des TreatmentData.calcIOB tut dann natürlich so, als wäre das Insulin frisch gespritzt worden und wendet die Aktivitätskurve darauf an - das passt natürlich nicht und führt zu einer falschen Darstellung des IOB.
Richtig eklig wird das ganze aber, wenn man (wie ich) mehrere Insuline verwendet und man quasi die RestIOB's aller Profile übertragen muss und dabei nicht einmal genau weiss, wie lange man zurückblicken muss ("normale" Insuline haben keine Wirkungsdauer über 24h aber mit "echten basalen Insulinen" kommen da doch mal 36h zusammen und dann müsste man sogar noch"vorgestern" ansehen.

Kurzum: die Kalkulation muss angepasst werden; die Frage ist nur wann und wer?
Willst Du dich dessen selbst annehmen oder soll ich es fixen und dir einen PR schicken? Einfachste Lösung wäre sicherlich einfach die Treatments der letzten x Stunden vor dem Kalkulationstag zu nehmen und das ganze einfach durchzurechnen, weil die TreatmentData.calcIOB scheint auch mit total überalterten Injektionen (also auch Treatments die in Bezug auf den Kalkulationszeitpunkt schon Tage alt sind) richtig umgehen zu können - sie liefert dafür einfach 0 IOB und 0 activity......

liebe Grüsse

**Comment by zreptil** [comment]
Sorry für die späte Antwort. Ich habe aktuell nicht mehr so viel Luft, um allem wie bisher nachzugehen. Wenn Du da eine Lösung hast, kannst Du mir die gerne zuschicken. PRs baue ich nicht ein, das weisst Du ja. Aber wenn Du mir Code schickst, ich den überprüft habe und weiss, was er tut, kann ich den durchaus reinnehmen. Ansonsten werde ich mir das anschauen, sobald ich wieder mehr Freiraum habe.

**Comment by gruoner** [comment]
da das ganze etwas mehr Codechanges nach sich ziehen wird, schicke ich dir einen PR. Dann siehst du was wo geändert werden muss und du kannst es in den Master einbauen.....

**Comment by gruoner** [comment]
hab den PR #47 dafür gebastelt

**Comment by zreptil** [comment]
Sollte mit Einbau des PR behoben sein.
