### ISSUE TITLE
Versions willwarr

### ISSUE THREAD

**Issue by gruoner** [zreptil/nightscout-reporter#48]
Hallo Andi

ich hab gard auf 2.12.0-1 upgerdaded und das Versionschaos fängt schon wieder an.... hast du bereits ein pubspec für 2.12?

liebe Grüsse

Resolving dependencies... (3.1s)
The current Dart SDK version is 2.12.0.

Because angular_components >=0.13.0 depends on observable ^0.22.2 and no versions of observable match >0.22.2 <0.23.0, angular_components >=0.13.0 requires observable 0.22.2.
And because observable 0.22.2 depends on dart_internal ^0.1.1, angular_components >=0.13.0 requires dart_internal ^0.1.1.
So, because dart_internal ^0.1.1 requires SDK version >=2.0.0-dev.12.0 <2.12.0 and nightscout_reporter depends on angular_components ^0.13.0, version solving failed.

**Comment by zreptil** [comment]
Hallo Torsten,

gut, dass ich das noch nicht upgegraded habe ^^ Ich habe zur Zeit nicht die
Zeit, mich um die Versionsprobleme zu kümmern, weshalb ich da bisher noch
auf der 2.10.5 bin. Wenn ich mal die Muse habe, schaue ich, was da Probleme
bereitet.

LG Andi

Am Sa., 6. März 2021 um 21:58 Uhr schrieb gruoner <notifications@github.com

**Comment by gruoner** [comment]
hatte vorher 2.10.5 und das lief auch nicht mehr - gab beim debug probleme; deploy hab ich nicht getestet.....

**Comment by gruoner** [comment]
hab jetzt ein wenig rumgespielt und mit webdev 2.5.9 und dart sdk 2.10.x funktioniert zumindest noch alles.
Aber sobald man auf SDK 2.12.x geht, scheint es Angular 6 (und components 1.x) zu brauchen und dann zerlegt es den kompletten NSR code - die Angular Jungs haben mit 6.0.1 offensichtlich extrem viel geändert und das müsste man im Code erstmal nachvollziehen. Ich hab aber das dumpfe Gefühl, dass das für meine 3 Featurebranches des NSR katastrophal kommt, weil ich auch die quasi neu implementieren müsste....

Kurzum: da steht eine Menge Arbeit an, weil "nicht auf Angular 6 und SDK > 2.10.x zu wechseln" ist ja auch keine Option - oder?

**Comment by zreptil** [comment]
Hallo Torsten,

ich hab mir das jetzt auch nochmal angeschaut. Aber auch nach mehreren
Stunden gibt es da keine Lösung. Angular 6.0 und Dart 2.12 sind soweit ich
das überblicke nicht miteinander kompatibel. Da passen einige
Abhängigkeiten in angular und angular_components nicht. Selbst ein komplett
neu erstelltes, leeres Projekt lässt sich nicht mit Angular 6.0 und Dart
2.12 kompilieren.

Da fehlt anscheinend noch so einiges, was die Bibliotheken nachziehen
müssen, damit das funktionieren kann. Ich denke, da bleibt nichts anderes
übrig, als erstmal abzuwarten, was da an Updates kommt und erstmal alles
genau so zu belassen wie es ist. Solange nichts davon komplett veraltet und
vom Browser nicht mehr unterstützt wird, gibt es auch keine Notwendigkeit,
da in grosse Hektik zu verfallen.

Irgendwann schaue ich mir das wieder an mit Dart 2.12 und Angular 6, aber
aktuell sind die Inkompatibilitäten zwischen beiden für mich nicht lösbar.
Das müssen die Bibliotheksentwickler machen.

LG Andi



Am So., 7. März 2021 um 14:10 Uhr schrieb gruoner <notifications@github.com

**Comment by zreptil** [comment]
Hallo Torsten,

weil ich gerade auch über das Problem gestolpert bin, nachdem ich mit Dart
2.12 rumgekaspert hatte: Ich konnte das auf einmal auch nicht mehr mit
meiner Original Konfiguration kompilieren. Das liegt daran, dass bei
Aktivierung von Dart 2.12 und einem Kompilierungsversuch der webdev-build
in einer höheren Version installiert wird und auch so bleibt. Der kann dann
mit den alten Versionen nichts mehr anfangen. Ich habe dann folgende Zeile
ausgeführt:

pub global activate webdev 2.5.9

Danach liess es sich wieder mit der Originalkonfiguration kompilieren. Das
muss man im Hinterkopf behalten, wenn man an den Versionen rumprobiert. Ich
werde in den nächsten Tagen noch einige Versuche machen, irgendwas mit
höherer Version zum Laufen zu bringen, aber derzeit sieht es wirklich
danach aus, als wenn die zugrundeliegenden Bibliotheken untereinander
Inkompatibilitäten haben, die nicht aufgelöst werden können.

LG Andi

LG Andi



Am Sa., 6. März 2021 um 22:22 Uhr schrieb gruoner <notifications@github.com

**Comment by gruoner** [comment]
gelöst mit #60
