### ISSUE TITLE
TDD IE in der Tagesstatikstik

### ISSUE THREAD

**Issue by nshtg** [zreptil/nightscout-reporter#49]
Hallo Andi,

die TDD IE in der Tagesstatikstik zeigt in der Zusammenfassung einfach die Summe der TDD. Würde es nicht mehr Sinn machen hier einen Durchschnitt anzuzeigen?

![Screenshot_20210308_195944](https://user-images.githubusercontent.com/5219415/110368116-df763a00-8048-11eb-869d-1afd84b61afd.png)

Viele Grüße,
nshtg

**Comment by zreptil** [comment]
Hallo nshtg,

das habe ich mir auch schon überlegt. Das müsste dann auch für Bolus und Basal gelten. Aber da bin ich noch am knobeln, wie ich das am Besten umsetze und wie das dann in der Spalte aussehen muss. Ich kann dann das Durchschnittszeichen verwenden, aber das funktioniert dann anscheinend auch nur in Deutsch, weil andere Länder das soweit ich das mitgekriegt habe nicht kennen. Deswegen muss da in englisch avg. stehen, was schon wieder den Platz für die Spalte vergrössert.

Da muss ich noch drüber nachdenken, wie das am Besten zu handhaben ist.

**Comment by zreptil** [comment]
Nach längerer Zeit habe ich mir das jetzt nochmal überlegt und denke, ich habe eine brauchbare Lösung. Mit der Version 2.0.8 ist das in der Tagesstatistik vorhanden.
