### ISSUE TITLE
neues Feature - Quotienten aus BZ-Anstieg und Insulinaktivität, BZ-Anstieg und Kohlenhydrataktivität (und vielleicht noch ein paar mehr)

### ISSUE THREAD

**Issue by gruoner** [zreptil/nightscout-reporter#52]
Hallo Andi

wir haben seit Anbeginn des T1D extreme Schwankungen im Blutzucker, den wir einfach nicht mit dem "normalen Standardmodell":
- Insulin senkt Blutzucker
- Kohlenhydrate erhöht ihn
- Sport bringt alles ein wenig durcheinander
- Stress und Angst etc. auch
nicht mehr erklären können.

Da wir ja nun eine Menge Daten vorliegen haben (hinreichend exakte BZ-Messungen, Insulininjektionen inkl. deren Wirkungskurve, Kohlenhydratzufuhr inkl. deren Wirkungskurven, sportliche Aktivitäten...) sollte es uns doch leicht fallen ein paar Quotienten sowohl an die Tageskurve zu kleben also auch ein Perzentildiagramm über diese Quotienten zu rechnen.....

**BZ-Veränderung / Insulinaktivität**: sollte ja die Insulinwirksamkeit wiederspiegeln (insb. wenn das letzte Essen lang genug zurückliegt)
**BZ-Veränderung / Kohlenhydrataktivität**: sollte ja umgekehrt die kohlenhydatwirksamkeit / -aufnahme wiederspiegeln (wird zwar etwas kniffelig, weil hier immer Insulinaktivität im Spiel ist, aber man kann die Kohlenhyrdataktivität auch mit der zeitlich gewichteten Insulinaktivität kombinieren und dann erkennen, wie bestimmte Lebensmittel wirklich wirken

Nun kann man diese beiden Quotienten auch in einer Perzentile über den ganzen Tag statistisch abbilden und so "sehen" wie die Wirksamkeiten über den Tag schwanken (insb. beim Insulin ist das extrem relevant; bei den Kohlenhydraten evtl. gar nicht mal so) und sich so einem zeitabhängigen Wirksamkeitsfaktor nähern, der die Vorhersage deutlich verbessern müsste.
Sicher gibt es noch ein paar mehr Faktoren zu berücksichtigen (Krankheiten, Sport, Stress....) aber die kann man ja auch über xdrip oder nightsout-server bereits heute erfassen und ins Modell mit einbeziehen.....

Wie siehst du das? Macht das Sinn oder spinn ich mir nur Zusammenhänge zusammen, wo keine sind?

lioebe Grüsse

**Comment by zreptil** [comment]
Sorry für die späte Antwort. Zur Zeit habe ich viel um die Ohren, was mich von solche komplexen Berechnungen abhält. Wenn Du dazu Formeln liefern kannst, die den Wirksamkeitsfaktor berechnen können, dann lässt sich sowas sicher einbauen. Allerdings sollte dabei auch berücksichtigt werden, dass Nightscout Reporter lediglich der Dokumentation dient, nicht der Berechnung zukünftiger Verläufe. Dazu gibt es andere Programme, die das wesentlich besser machen.

Aber wenn Du mir sagen kannst, wie ich was aus den vorhandenen Daten zusammenrechnen soll, um eine bessere Darstellung zur Auswertung zu liefern, dann schaue ich mir das gerne an, wenn ich wieder Luft habe und falls es mir gelingt, den Mehrwert darin zu entdecken, dann werde ich das mit Freuden zu Nightscout Reporter hinzufügen.

Falls es mir nicht gelingt, den Mehrwert zu entdecken, werde ich Dir auf alle Fälle sagen, wieso das so ist und lasse mich dann durchaus auch eines besseren belehren :)

**Comment by gruoner** [comment]
was ich hier vorhabe (oder was mir im Kopf rumschwirrt) ist nur eine etwas ausgefeiltere Nutzung der Daten des Nightscout - aber mal von vorn angefangen:
alle Insulintherapie setzt auf der Idee auf, durch Zuführung der "korrekten" Menge Insulins zum "richtigen" Zeitpunkt den Blutzuckerverlauf ohne "grössere Ausschläge" im Zielbereich zu halten - so abstrakt so unbrauchbar.....
Um dieses Problem zu lösen, haben sich eine handvoll Therapien durchgesetzt, die aber fast ausschliesslich (nämlich alle bis auf die Closed-Loop-Systeme) darauf aufsetzen
a. beobachte den Menschen über einen längeren Zeitraum von vielleicht 2 Wochen sehr detailliert,
b. errechne daraus ein Standard-Injektionsmodell mit einem Standard-Tagesablauf und einem Standard-Essensmodell und
c. hoffe, dass sich am Metabolismus des Menschen über die nächsten Jahre nicht viel ändert
Das mag vielleicht bei "fertig gebackenen Erwachsenen mit einem absolut geregelten Bürojob" funktionieren, aber sicher nicht mit 6-jährigen Kindern, bei denen jeder Tag anders ist - vom Verständnis über die Zusammenhänge in ihrem Körper und ihrer Krankheit mal ganz zu schweigen.
Zudem setzen diese Therapien auf der Annahme auf, dass es nach einem kurzen aber extrem gut überwachbaren einen sehr langen, nur lausig überwachbaren Zeitraum gibt - mit zunehmender Digitalisierung (und ich bin mir nicht mal sicher, ob dies hier diese Bezeichnung schon verdient) wie CGM's, weitgehend präzisen Insulinprofilen von sehr präzisen Injektionsmengen und Zeitpunkten dieser Injektionen sowie einer immer präziseren Kalkulation von Kohlehydratmengen und Kohlenhydratarten stimmt diese Annahme aber nicht mehr und wir können andere Therapien in Erwägung ziehen oder zumindest den Tagesablauf, Essensmodell etc. flexibilisieren.......
Wir haben heute mit CGM's, digitalen Diabetestagebüchern wie xDrip und der zunehmende Verbreitung von Smartwatches mit Schrittzählern, Pulsmessern und sogar Körpertemperatursensoren eine so gigantische Überwachungstechnologie an der Hand, dass wir deren Daten (neben sie den Tech-Konzernen in den Rachen zu werfen) auch selbst zur Flexibilisierung oder Optimierung unserer Diabeteswelt verwenden können - wir müssen dafür "nur" ein bisschen Datascience betreiben und die Algorithmen zur Datenextraktion "erfinden" und "mit einer verständigen Community" diskutieren. Um nichts anderes geht es hier......

**Comment by gruoner** [comment]
mein erster Schritt hier folgt der Präzisierung der Insulinaktivitätsmodelle:
Wenn man präziser "weiss" wie ein Insulinpräparat "wirkt", kann man dessen Verlauf besser vorhersagen - nichts anderes macht der tageszeitabhängige ISF. Der ISF sagt eigentlich nichts anderes aus als "wieviel Blutzucker vermag eine Einheit Insulin zu reduzieren?" und dass dies sowohl Praparat- als auch tageszeit- (bisweilen sogar tagesform-) abhängig ist, ist offensichtlich.
Den ISF zu ermitteln ist ein komplexes (und für den Patienten abstrengendes) Unterfangen und setzt (wiedermal) auf der Annahme auf, man müsse dies anhand einiger weniger Messpunkte zwischen Injektion und vollständiger Absorbtion der Injektion tun - mit einem CGM, einer präzisen Injektion und einem hinreichend präzisen Aktivitätsmodell des Präparats braucht es das nicht mehr. Die Statistik löst die Komplexität für uns auf......

Unter der Annahme, dass
a. die letzte Mahlzeit entweder lang genug zurückliegt (um nicht mehr für eine Blutzuckerveränderung verantwortlich zu sein) oder die letzte Mahlzeit ist in ihrer Blutzuckerveränderung hinreichend präzise zu kalkulieren
und
b. körperliche Aktivitäten und krankheitsbedingte "Dreckeffekte" ausgeschlossen sind
kann man aus dem Quotient von Insulinaktivität (also die erste Ableitung der Insulin-an-Board-Kurve) und Blutzuckerveränderung zum gleichen Zeitpunkt den ISF zu diesem Zeitpunkt berechnen.
Nun sollte man dies bei der Ungenauigkeit sowohl der CGM-Werte und Insulinaktivitäten nicht Messpunkt-für-Messpunkt machen - das ergäbe eine "Fieberkurve" aus der man nichts herauslesen kann - aber mithilfe eines "sliding Window" von vielleicht 15 minuten vorher und 15 minuten hinterher glättet sich die Linie. Interessant sind dann auch die Quotienten mit inversem Vorzeichen (wenn trotz Insulinaktivität eine Blutzuckersteigerung stattfindet) - das sind Hinweise auf Verletzungen der Vorbedingungen.....
Damit bekommen wir für jeden Zeitpunkt des Tages entweder einen so geglätteten Quotienten (als Indikator für die Blutzuckerreduktion je Insulineinheit) oder eben gar keinen Wert (wenn die Vorbedingungen oben nicht erfüllt sind).
Über diese Werte kann man nun (analog den Blutzuckerwerten) eine Perzentile visualisieren und erhält somit für den betrachteten Zeitraum eine hinreichend präzise Kalkulation des ISF zum Zeitpunkt des Tages. Mit ein wenig Kniff, bekommt man das auch bei Multi-Insulin-Therapien für jedes einzelne Insulin hin, aber bei den basalen Präparaten wird die Einhaltung der Vorbedingungen kniffelig, weil da die Bolusinjektionen zu "Dreckeffekten" in der Wirkung der basalen Injektionen führen. U.U. brauchen wir das ganze aber für die basalen Insuline gar nicht, weil wir für die ja andere Kalkulationsmechanismen /-techniken haben......

Was ich nun tun möchte, ist einerseits die geglättete Quotientenkurve in die Tageskurve einzeichnen und andererseits eine Übersicht über die Perzentile aller geglätteter Quotienten pro Tageszeit (also nur die Quotienten, wo auch die Vorbedingung erfüllt ist).

Das ganze greift aber extrem tief in den Code des NSR ein (insb. weil ich für "Multi-Insuin" bereits viele Funktionen den IOB-betreffend austauschen musste) und wenn wir das nicht im Master machen, müsste ich mich mit meinem Tree vom Master verabschieden, weil ich deine Changes nicht jedesmal von Hand in meinen Tree hinüber tragen kann - das ist jetzt schon ein gröberer Aufwand, den ich nur noch bei wichtigen Bugfixes oder grösseren Releases mache. Mit dem hier wäre auc das vorbei und diesen Weg geh ich nur, wenn es keine andere Möglichkeit gibt......

**Comment by gruoner** [comment]
jetzt darf man aber eines nicht ausser Acht lassen - was mit den Insulinen geht, geht auch mit den Kohlenhydraten; halt unter umgekehrtem Vorzeichen und unter der Annahme, dass man den ISF des Boluspräparates hinreichend präzise kennt und dessen Einfluss auf den Blutzucker kalkulieren kann.
Ich will also später (wenn Multi-Carbs deployed ist) auch für die Kohlenhydrate machen......
