### ISSUE TITLE
Glucose objectives

### ISSUE THREAD

**Issue by legrand572** [zreptil/nightscout-reporter#54]
Hello, I really like to use your app, it's really usefull when I go to my doctor.

However my doctor talked me about a way to quantify continuous glucose data he would like to see.

It consist of a percent table of glucose data %:

- \> 250         (objective <5%)
- 180 - 250   (objective <25%)
- 70 - 180     (objective >70%)
- 54 - 70       (objective <4%)
- < 54           (objective <1%)

I could use custom glucose objective to manually calculate each % but I am quite sure it is not too complicated for you to add this analysis to reports :)

I foud this as reference (but you can find it elswhere):
https://care.diabetesjournals.org/content/42/8/1593
![F1 large](https://user-images.githubusercontent.com/8424847/121300441-21887380-c8f7-11eb-839b-9e8f2bd1021c.jpg)

Thank you for all your work !

**Comment by zreptil** [comment]
Hi legrand,

in fact you can see this on the analysis page. All you have to do is to set the option "Standard range with finder gradation" in the options for analysis. Then the standard target area is divided in the sections you mention.

**Comment by legrand572** [comment]
Wow, I didn't even noticed there was those options... you really did a great work!! Many thanks :)

**Comment by zreptil** [comment]
You are very welcome :) This option is there, because another user pointed me to this. I also have to thank you (my users) for the great input you deliver for making nightscout reporter better :)
