### ISSUE TITLE
eventtype "question"

### ISSUE THREAD

**Issue by gruoner** [zreptil/nightscout-reporter#56]
im Nightscout selbst kann man eine Frage erfassen - das läuft dann auf ein Treatment vom eventType "Question" hinaus und im "notes" Feld steht dann die eigentliche eingegebene Frage drin.
Heute druckt der NSR das einfach blank als note an.

Damit man Fragen später im Ausdruck / Report von normalen Notizen unterscheiden kann, wäre es extrem hilfreich, die note zu einer Question mit einem Präfix "Frage:" (oder bei Mehrsprachigkeit in der entsprechend eingestellten Sprache) zu versehen. Bsp. "Frage: was zum Henker ist hier schief gegangen?".
Da man in den PDFs am Ende sogar suchen kann, macht das die Besprechung mit der Diabetologin noch komfortabler.....

Bevor ich das wieder in meinen eigenen Code reinmurkse, was hältst du davon? Lässt sich das einfach umsetzen?

liebe Grüsse
Torsten

**Comment by zreptil** [comment]
Den eventType kannte ich gar nicht. Das ist schon eine gute Idee, sowas verfügbar zu machen. Aber ob die Tagesgrafik dafür geeignet ist? Hmmm ... das muss ich mal überlegen. Die könnte damit noch weiter überladen werden, aber ich denke, für eine Analyse wäre das durchaus hilfreich. Ich denk mal drüber nach, wie sich sowas am besten umsetzen lässt.

Für meine eigenen Tests: Was für Fragen schreibst Du da beispielsweise rein und wie oft kommt sowas vor?

**Comment by gruoner** [comment]
wenn's in der Tagesgrafik steht, hat man halt den kompletten Kontext zur Frage vor sich.
btw. es kann wirklich sein, dass dieser Eventtype erst in Nightscout Server 14 dazugekommen ist. Ich kannte ihn vorher auch nicht, aber meine Frau benutzt ihn häufig, wenn sie Gedankenstützen für das Gespräch mit der Diabetologin braucht. So einmal die Woche kann das schon vorkommen; meist wenn irgendetwas kompett unlogisch (z.B. Insulin gespritzt, nix gegessen und dennoch durch die Decke gegangen) oder etwas widererwartend extrem gut gelaufen ist. Der Text ist dann eher ein kurzer Satz aus 3-4 Worten und heute wird das einfach als normales Note angedruckt - prinzipiell schon gut, aber man erkennt es nicht unter der Fülle von Tagesgrafiken (90 für ein Quartalsgespräch) und den "normalen" Notizen darin.
Darum wäre es ja cool, wenn man diese Fälle einfacher erkennen kann und schwerer übersieht.......

**Comment by gruoner** [comment]
hast du Dir schon eine Meinung dazu gebildet? Wenn du's nicht aufnehmen willst, fang ich demnächst an es in meinen CustomCode reinzupfriemeln
