### ISSUE TITLE
Vorschlag: Option um SMB zu Basalrate zu zählen

### ISSUE THREAD

**Issue by mxsrm** [zreptil/nightscout-reporter#59]
Wenn man AAPS mit SMB nutzt, ist zwangsläufig die Basalrate immer extrem niedrig (im Vergleich zum Bolus). Wäre es möglich hier eine Option einzubauen, um (je nach Gusto) die SMB zur Basalrate zählen zu lassen? Der Loop nutzt die Temprate von 0% ja u.a. für SMB.

Bolus ist für mein Verständnis nur das, was ich wirklich willentlich abgebe und der Rest ist ja das, was das System für mich macht.

Gruß!

**Comment by zreptil** [comment]
Theoretisch schon, aber SMB heisst ausgeschrieben Super Micro Bolus. Da scheint mir das dann doch eher auch von der Verwendung her zum Bolus zu gehören. Da hielte ich das Dazuzählen zum Basal für eine mittelschwere Themaverfehlung. Aber wenn man mir das gut begründen kann, dann kann ich drüber nachdenken, so eine Option reinzubauen.

**Comment by mxsrm** [comment]
SMB "leiht" sich das Basalinsulin aus der Zukunft (um UZ zu vermeiden) und gibt sie als Microbolus ab; damit fehlt es aber natürlich in der Berechnung der Basalrate, obwohl es natürlich trotzdem dazu gehört. 

Das führt dann z.B. bei mir häufig zu völlig abstrusen Werten für Basal & Bolus (hier zb knapp 20,5h 0% temp basal rate wegen SMB):

![image](https://user-images.githubusercontent.com/7951225/145631017-ab7f6ddc-dfd7-4ecb-a7d7-546525b716ff.png)

Damit verliert die Einteilung in Basal und Bolus natürlich völlig ihre Bedeutung.

**Comment by mxsrm** [comment]
Eine alternative Idee wäre die SMB aus dem "Bolus ges." zu nehmen und stattdessen eine zusätzliche % Angabe einzuführen "SMB ges.". Das würde es vielleicht sogar noch deutlicher machen.
