### ISSUE TITLE
Dart Version

### ISSUE THREAD

**Issue by psychomom** [zreptil/nightscout-reporter#60]
Welche Version von Dart benötigt die aktuelle Version? Welche Version sollte für WebDeb verwendet werden?

**Comment by zreptil** [comment]
Die Dart Version ist 2.12.4 und WebDev wird in der Version 2.7.2 verwendet,

**Comment by gruoner** [comment]
bei mir funktionierts mit 2.12 und WebDev 2.7.2 - wann hast du den Upgrade auf 2.7.9 und den aktuellen Dart SDK geplant?

**Comment by gruoner** [comment]
nach dem grossen Umbau lässt es sich wieder nicht mehr kompilieren - welche Dart Version müssen wir nehmen?

**Comment by zreptil** [comment]
Nach welchem Umbau? Diese Projekt hier hat sein Lebensende erreicht. Ich habe es nicht mehr geschafft, die Angular Dart Versionen und das Material von Dart upzudaten, weshalb das hier auch nicht mehr weiter entwickelt. wird. Das Projekt unter https://github.com/zreptil/nightscout-reporter-angular ist das, was ich weiter entwickle. Da findet sich kein Dart drin, weil Dart leider ziemlich tot ist.

**Comment by gruoner** [comment]
korrigiere mich: mit 2.12.4-1 und webdev 2.7.2 gehts
