### ISSUE TITLE
CGP falsche Skala

### ISSUE THREAD

**Issue by mxsrm** [zreptil/nightscout-reporter#61]
Hi Andi,

mir ist ein kleiner Fehler bei den CGPs aufgefallen; das Pentagramm bei gesunden Menschen startet bei NR bei 130 statt bei 90 wie im Original.

![image](https://user-images.githubusercontent.com/7951225/166117613-4461f5f8-0471-4230-844d-e5fc99a4f69e.png)
<img width="519" alt="image" src="https://user-images.githubusercontent.com/7951225/166117623-92d9489d-827b-4e28-ac7d-b5b8f3d13d61.png">

LG

**Comment by zreptil** [comment]
Hi, mxsrm,

danke für den Hinweis. Das ist in der Tat etwas 
, was nicht ganz korrekt ist. Durch die nicht lineare Skalierung der Achse sieht der Graph zwar bei dem korrekten Wert von 90 nicht wesentlich anders aus, aber das ist in Version 2.2.1 korrigiert.

LG Andi
