### ISSUE TITLE
500 Internal Server Error - mal wieder

### ISSUE THREAD

**Issue by mxsrm** [zreptil/nightscout-reporter#67]
Hallo Andi,

ich habe aktuell das Problem, dass ich keine Übersicht mehr über 3 Monate erstellen kann, da es bei der Generierung zu dem bekannten 500 Internal Server Error kommt.

Das Problem wird sein, dass es zu viele Daten sind. Leider hilft das Stellen des Reglers auf "Klein" für die PDF Größen nicht, da das System die Tagesgrafiken nicht splittet und trotzdem versucht diese alle in ein PDF zu packen - was dann natürlich fehlschlägt.

Beispiel: Regler ist ganz nach links, das erste PDF wirft den 500er Fehler aus, ab dem zweiten PDF kommen dann schon die Wochengrafiken.
![image](https://user-images.githubusercontent.com/7951225/193405287-34a218c4-7b3b-414b-8b97-d479bf6c3273.png)

Testversion ist die aktuelle beta (https://nightscout-reporter.zreptil.de/beta/).

Ich schicke dir gleich eine Mail mit Token + Settings Config damit du es bei dir reproduzieren kannst. Browser ist aktuellster Chromium unter Arch Linux mit 32 GB RAM.

LG

**Comment by zreptil** [comment]
Hi Max,

danke für den Hinweis. Das liegt in dem Fall daran, dass Du bei den Tagesgrafiken Zwei pro Seite ausgewählt hast. Wenn Du eine auswählst, dann klappt es. Da stimmt was nicht mit der Berechnung der Grössen, wenn mehr als eine Grafik pro Seite ausgegeben werden. Das werde ich mir anschauen. 

Inzwischen gibt es drei Sachen, die Du machen kannst: in den Optionen für die Tagesgrafik nur eine pro Seite ausgeben lassen, eine kürzere Zeitperiode wählen oder die Tagesgrafiken alleine ausgeben lassen und die anderen PDFs zusammen. 

LG Andi
