### ISSUE TITLE
Download buttons not separated

### ISSUE THREAD

**Issue by hannesvoss** [zreptil/nightscout-reporter#68]
Hello there,

I do have an issue with the displayed download buttons.
Whenever I hit the first of two buttons, both display as 'clicked' and the download for the second part starts.
I tested it on both the normal and the beta version of the reporter.
It happens on Firefox (Version 107.0) and Chrome (Version 107.0.5304.110).

Do you have an idea where the bug originates from?
I did not have that issue the last time I was using it (around 3 months ago).

Best,
Hannes

**Comment by zreptil** [comment]
Hi Hannes,

up to now, I don't know anything about this. First of all: what buttons do you mean? The Buttons when a pdf is split in multiple downloads? At my system they work as intended. Could you provide me with the settings of your system, so that i can reproduce this issue on my system. Either as screenshots from the settings and the output parameters or export from the settings. Then I can see, if this error is reproducable at my site.

**Comment by hannesvoss** [comment]
Hi there,
I recorded a small GIF for you to show what I mean.
I also attached my settings (without private data).

![bug](https://user-images.githubusercontent.com/16735785/203857093-02f23a01-1ba7-419d-9620-d6b82ae54fdb.gif)
![Screenshot 2022-11-24 at 20-33-37 Nightscout Reporter](https://user-images.githubusercontent.com/16735785/203857106-24cbeecc-43bd-4583-a517-1b2933ce5333.png)
![Screenshot 2022-11-24 at 20-57-53 Nightscout Reporter](https://user-images.githubusercontent.com/16735785/203857113-b7e676cd-d34a-44b4-913b-8d5a594a132c.png)

**Comment by zreptil** [comment]
Hi Hannes,

thanks for the demonstration. I was able to reproduce the error. The reason for the error is that you have selected to open the pdf in the same window. This is needed on smartphones, but not very useful when working in a browser. If you don't select this option in the Output parameters, then the buttons will work independent. At least they do it in my environment. I think, i will remove this option, when releasing the next version that will be based on angular without dart. 

I hope it also works for you.

kind regards
Andi

**Comment by hannesvoss** [comment]
Hi Andi,

thanks for your quick response!
It works for me too now, so I'll close the issue :)

Best,
Hannes
