### ISSUE TITLE
Could the main functionality of the tool be migrated to CLI?

### ISSUE THREAD

**Issue by Nuddel69** [zreptil/nightscout-reporter#71]
I generate the same report every time, but it'd be easier to just fill in a configuration file and having a CLI script generating the PDF. Would it be possible to migrate the main generation part to a self-contained tool?

**Comment by zreptil** [comment]
Hi, Nuddel69,

for this purpose there are the shortcuts in nightscout reporter. With
shortcuts you define forms and period and by calling
https://nightrep.zreptil.de/shortcut?name=[nameofshortcut] you get the
specified PDF. You can read about the shortcuts in "What happened up to
now..." in Nightscout Reporter.

kind regards
Andi

Am Mo., 17. Juli 2023 um 16:47 Uhr schrieb Nuddel69 <
***@***.***>:
