### ISSUE TITLE
Glucose Percentile Diagram - Target area overlaps

### ISSUE THREAD

**Issue by thebarefootboy** [zreptil/nightscout-reporter#73]
Purely a cosmetic/aesthetic issue.

Just had a very rare week where my percentile diagram data didn't exceed 9 mmol/L.

However this causes the graph to max out at 9 mmol/L but the green target area still covers the area that would be 3.9-10 mmol/L. 

This causes the green area to overlap the title/header region of the page. [See screenshot.]
![Screenshot 2024-02-26 210446](https://github.com/zreptil/nightscout-reporter/assets/58922581/aaaaf667-e41c-4fe2-8aa7-ef5b180ab465)

**Comment by zreptil** [comment]
Thanks for the bugreport. 😃👍 It is fixed now and the target area will not overflow in the header anymore.

**Comment by zreptil** [comment]
This repository is meanwhile obsolete, so you will not find the fix here in this code. The current code can be found at: https://github.com/zreptil/nightscout-reporter-angular

There the fix is available.
