### ISSUE TITLE
Feature Wunsch: sanitized report for official documentation

### ISSUE THREAD

**Issue by LongboatAline** [zreptil/nightscout-reporter#8]
I just recieved a letter from the MD (Medizinischer Dienst/Germany) to hand in my reports for the past three months, detailing TDD, daily carbs, the whole works in order to get cgm approval.

Now the report would fit that perfectly (Yay!) if it didn't expose all those little smb's and blanks in the basal rate...

So the rather simple idea for that kind of official documentation would be to be able to 
a) turn off display of SMB
b) either display the basal rate, or (advanced) use an approximation of the SMBs given over a period to display as basal rate. (Problem would be, that done correctly, that would display way more changes in the basal rate than plausible for manual intervention)
c) for what it is worth - at least with a ZT Loop (Zero Temp, using *only* SMB, the basal rate is displayed completely off anyway - I'll write a separate issue on that though, and refere here)

**Comment by zreptil** [comment]
a) will be no problem. I will make it configurable in the options of the daily graphic, will be there in the next beta version
b) could be achieved by unchecking "Daily basalrate" in the options of the daily graphic. Then the basalrate of the profile will be displayed for the day without the temporary adjustments of the loop. Maybe this could be the fake the MD needs to be happy ^^
c) i would be very interested if you can give me information what this should look like and how to calculate it. It is no problem to exchange the basal display for another type of display derived from the data given.

btw: if it is easier for you (for me it is for sure ^^) we can talk in german about this.

**Comment by LongboatAline** [comment]
* a) Danke!
* b) probiere ich sofort aus ... löst das Problem mit dem MD :)
* c) bin gerade durch den "webdev build" zur 1.2.5a durch. Im Changelog stand etwas von korrigierter Basalratenberechnung - ich schaue einmal, ob das etwas geändert hat, und mache die Screenshots mit der Version.

**Comment by LongboatAline** [comment]
c) Ist größtenteils bereits korrigiert, klasse! Ein Problem scheint noch zu sein, wenn die TBR die Tagesgrenze überschreitet, fängt der Reporter das Blatt des nächsten Tages mit der in Nightscout eingetragenen Default-BR an:

![basal v 1 2 5a - nightscout reporter](https://user-images.githubusercontent.com/35570803/53238310-49595c00-3699-11e9-84dc-bb3cbc7eb5aa.jpg)

Dabei fällt noch ein
* d) auf: Könnte man die Darstellung der Kommentare entweder ganz abstellen, oder aber auf bestimmte Gruppen einschränken? (z.b. nur an bolus/carb entry gekoppelte? Nach Uploader herausfilterbar?)

**Comment by LongboatAline** [comment]
So sah das übrigens mit der 1.2.5 aus:
![basal v 1 2 5 - nightscout reporter](https://user-images.githubusercontent.com/35570803/53239129-84f52580-369b-11e9-8387-e4c1d9765362.jpg)


oopsie. 
* f) Kannst Du bitte auch die e-carbs tarnen? ;-)

**Comment by zreptil** [comment]
d) Die Kommentare kannst Du mit "Notes" in den Optionen der Daily Graphic komplett abschalten

Die anhand des Uploaders abschaltbar machen ist eine interessante Idee. Denn einige Uploader sind in der Tat extrem mitteilungsfreudig. Ich muss mir aber überlegen, wie ich das so mache, dass es für den Benutzer möglichst einfach ist. Texteingaben gefallen mir nicht. 

Das Problem bei c) mit der TBR über den Tageswechsel hinweg kannst Du umgehen, indem Du den Tag vorher auch noch lädst. Eventuell lasse ich mir da aber noch was einfallen, um das zu kompensieren. Allerdings ist das komplizierter, als es zunächst den Anschein haben könnte ^^

**Comment by LongboatAline** [comment]
d) habe ich entdeckt. funktioniert prima, danke!

Das war ein Tag aus der "Mitte" des Reportes, d.h. der Vortag war geladen. Jeder Tag fängt mit einem "Fitzel" BR an, bevor sie dann auf 0 gesetzt ist. 

![basal v 1 2 5a tagesanfang - nightscout reporter](https://user-images.githubusercontent.com/35570803/53240218-65abc780-369e-11e9-9c48-14fd11b83e52.jpg)

Für den MD kann ich die BR auch ganz abschalten, wunderbar. Ich muss mal eine TBR setzen, denn ich hatte (vor einigen Versionen) den Eindruck, dass auch immer die in Nightscout hinterlegte Profil-BR angezeigt wird, egal ob die gewählte BR nun höher oder tiefer liegt. (aufgefallen, weil in "echt" ein Local Profile aus AAPS zur Anwendung kam, das davon abwich)

**Comment by zreptil** [comment]
Prima, vielen Dank für den Hinweis mit der fortlaufenden Rate. Ist mir noch gar nicht aufgefallen, aber beim Drüber nachdenken habe ich eine ungefähre Vorstellung, wo das schief läuft. Werde ich mir anschauen. 

Die Basalrate ist in der Tat immer die aus Nightscout. Wenn AAPS ein lokales Profil hat, das nicht in die Nightscoutdaten einfliesst, dann weiss Nightscout Reporter nichts davon. Ich verwende zwar selbst AAPS, aber ich verwende nur Daten von Nightscout dafür. Auf andere Datenquellen kann Nightscout Reporter nicht zugreifen.

**Comment by zreptil** [comment]
Die Ausblendung der SMB-Werte ist in der aktuellen Beta-Version auf dem Server verfügbar.

**Comment by zreptil** [comment]
Das Problem mit der TBR über den Tageswechsel hinweg wird in issue #17 weiter behandelt.
