### ISSUE TITLE
SMB: Bad state no element

### ISSUE THREAD

**Issue by LongboatAline** [zreptil/nightscout-reporter#9]
In mehreren Kombinationen getestet: sobald "SMB an der Kurve platzieren" deselektiert wird, kommt bei einigen Datenkonstellationen anstelle der Tagesgraphen eine Fehlerseite, beginnend mit "Bad state No element", gefolgt von einer ganzen Seite von Verweisen auf main.dart.js

Ich konnte das auf einen bestimmten Tag eingrenzen, so sieht er mit den SMBs *an* der Kurve aus:

![no element error if off curve - nightscout reporter](https://user-images.githubusercontent.com/35570803/53241670-b1607000-36a2-11e9-9de0-ce263f565126.jpg)

**Comment by LongboatAline** [comment]
Fehlermeldung:
![no element - nightscout reporter](https://user-images.githubusercontent.com/35570803/53241785-0bf9cc00-36a3-11e9-86ba-766c1bb5a30c.jpg)

**Comment by zreptil** [comment]
Das krieg ich bei mir nicht hin. Kannst Du mir den Link zu Deinen Daten zukommen lassen und den Tag an dem der Fehler auftritt? Das ist vermutlich irgendwas, was da Datentechnisch nicht ganz korrekt verarbeitet wird.

**Comment by LongboatAline** [comment]
Danke, habe ich Dir geschickt. So sieht übrigens Tidepool den Tag (uploader xDrip)

![tp 2019 02 20 - unknown](https://user-images.githubusercontent.com/35570803/53246198-49188b00-36b0-11e9-8855-9c3c51e551ca.jpg)
